jobs:
  - name: hello_world
    type: runSh
    steps:
      - TASK:
        - script: echo "Hello World!!!"
  - name: increase_size
    type: runSh
    runtime:
      container: false
    steps:
      - TASK:
        - script: truncate -s 30G $(uuidgen)
        - script: df -h
