jobs:
  - name: hello_world
    type: runSh
    steps:
      - TASK:
        - script: echo "Hello World!!!"
  - name: increase_size
    type: runSh
    runtime:
      container: false
    steps:
      - TASK:
        - script: apt-get install -y -q xfsprogs
        - script: xfs_mkfile 10240m $(uuidgen)
        - script: df -h
        - script: ls
